### PR TITLE
Huge redo + Added entries from another MK list

### PR DESCRIPTION
**Pull request by DandelionSprout**
Essentially, I feel that pretty much every language on the planet (Especially those who have Firefox or Chrome translations) should have an adblock list included in at least one adblocker.

Currently there seems to be 2 Macedonian lists out there (of which your list is one of them), neither of which currently seem like a clearcut candidate for AdGuard or AdBlock, let alone uBlock Origin with how strict those guys have been in the past couple years.

So in an attempt to kickstart things again and have another language be represented in extensions, I carried over entries from [the other Macedonian list that I know about](https://github.com/cchevy/macedonian-pi-hole-blocklist/blob/master/hosts.txt), which has been kept much more actively maintained, but which has too few entries to make it into extensions (except "AdGuard Home")

I also ran the resulting list through https://abp.surge.sh/redundantRuleChecker/, leading to a more lean and slim list.

### CODE REVIEW

**Comment by DeepSpaceHarbor** [comment]
@DandelionSprout thank you for bringing the project back to life.

**Comment by MasterKia** [comment]
> I also ran the resulting list through https://abp.surge.sh/redundantRuleChecker/, leading to a more lean and slim list.

@DandelionSprout The link is dead, is there a new site?

**Comment by DandelionSprout** [comment]
Thankfully there is: https://abpvn.com/ruleChecker/redundantRuleChecker.html

**Comment by MasterKia** [comment]
Thanks. I presume this doesn't take into account uBO syntax.

**Pull request merged**
